# Generated by Django 4.1.6 on 2023-03-14 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='grade',
            name='put_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
