# Generated by Django 4.1.6 on 2023-03-14 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0003_alter_grade_assignment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='assignment_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservice.assignment'),
        ),
    ]
