# Generated by Django 4.1.6 on 2023-03-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0006_rename_assignment_grade_assignment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
